# Data Preprocessing

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
import os

os.chdir("/Users/obadaessa/Desktop/Internship/Data Sets")
os.getcwd()

'/Users/obadaessa/Desktop/Internship/Data Sets'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
x = dataset.iloc[:, 3:13]

In [6]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [7]:
x = x.values

In [8]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y = dataset.iloc[:,13].values

In [38]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [10]:
dataset.isnull()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
0         False       False    False        False      False   False  False   
1         False       False    False        False      False   False  False   
2         False       False    False        False      False   False  False   
3         False       False    False        False      False   False  False   
4         False       False    False        False      False   False  False   
...         ...         ...      ...          ...        ...     ...    ...   
9995      False       False    False        False      False   False  False   
9996      False       False    False        False      False   False  False   
9997      False       False    False        False      False   False  False   
9998      False       False    False        False      False   False  False   
9999      False       False    False        False      False   False  False   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      False    False          False      False           False   
1      False    False          False      False           False   
2      False    False          False      False           False   
3      False    False          False      False           False   
4      False    False          False      False           False   
...      ...      ...            ...        ...             ...   
9995   False    False          False      False           False   
9996   False    False          False      False           False   
9997   False    False          False      False           False   
9998   False    False          False      False           False   
9999   False    False          False      False           False   

      EstimatedSalary  Exited  
0               False   False  
1               False   False  
2               False   False  
3               False   False  
4               False   False  
...               ...     ...  
9995            False   False  
9996            False   False  
9997            False   False  
9998            False   False  
9999            False   False  

[10000 rows x 14 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
lb = LabelEncoder()

In [13]:
lb2 = LabelEncoder()

In [14]:
x[:,1] = lb.fit_transform(x[:,1])
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [15]:
x[:,2] = lb2.fit_transform(x[:,2])
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
# Use ColumnTransformer WITH OneHotEncoder

from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
x = x[:,1:]

In [18]:
x[1,:]

array([0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [19]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3, random_state=0)

In [20]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [21]:
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()

In [24]:
xtrain.shape

(7000, 11)

In [27]:
# Input layer

model.add(Dense(input_dim=11,
                kernel_initializer='random_uniform', 
                activation='relu', 
                units=15))

# Hidden layer

model.add(Dense(units=8, 
                kernel_initializer='random_uniform', 
                activation='relu'))

# Output layer

model.add(Dense(units=1, 
                kernel_initializer='random_uniform', 
                activation='sigmoid'))

model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [29]:
model.fit(xtrain, ytrain, epochs=50, batch_size=32)

Epoch 1/50
219/219 [==============================] - 0s 551us/step - loss: 0.6236 - accuracy: 0.7971
Epoch 2/50
219/219 [==============================] - 0s 547us/step - loss: 0.5501 - accuracy: 0.7977
Epoch 3/50
219/219 [==============================] - 0s 534us/step - loss: 0.5230 - accuracy: 0.7977
Epoch 4/50
219/219 [==============================] - 0s 530us/step - loss: 0.5121 - accuracy: 0.7977
Epoch 5/50
219/219 [==============================] - 0s 544us/step - loss: 0.5075 - accuracy: 0.7977
Epoch 6/50
219/219 [==============================] - 0s 533us/step - loss: 0.5054 - accuracy: 0.7977
Epoch 7/50
219/219 [==============================] - 0s 527us/step - loss: 0.5044 - accuracy: 0.7977
Epoch 8/50
219/219 [==============================] - 0s 536us/step - loss: 0.5040 - accuracy: 0.7977
Epoch 9/50
219/219 [==============================] - 0s 533us/step - loss: 0.5038 - accuracy: 0.7977
Epoch 10/50
219/219 [==============================] - 0s 533us/step - loss: 0.503

In [30]:
ypred = model.predict(xtest)

In [31]:
ypred = (ypred>0.5)

In [32]:
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [33]:
ytest

array([0, 1, 0, ..., 0, 0, 1])

In [34]:
yp = model.predict(sc.transform(np.array([[0,1,100,1,25,8,115000,24,1,1,100000]])))

In [35]:
yp

array([[0.20154402]], dtype=float32)

In [36]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, ypred)
print(cm)

[[2379    0]
 [ 621    0]]


In [37]:
from sklearn.metrics import accuracy_score
print(accuracy_score(ytest, ypred))

0.793
